import java.text.SimpleDateFormat
import java.util.Date
import org.gradle.jvm.tasks.Jar

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the idea plugin, used for form builder
    idea
    // Apply the application plugin to add support for building an application
    application

    //Shadow plugin for fatJar
    id("com.github.johnrengelman.shadow") version ("6.1.0")
}

project.ext {
    set("mainClassName", "org.hvdw.jimagefuser.Application")
}

repositories {
    mavenCentral()
    jcenter()
    maven("https://www.jetbrains.com/intellij-repository/releases")
    maven("https://jetbrains.bintray.com/intellij-third-party-dependencies")

}


dependencies {

    //// Log4J and SLF4J configuration dependencies.
    implementation(group = "org.slf4j", name = "slf4j-api", version = "1.7.30")
    implementation(group = "org.slf4j", name = "slf4j-simple", version = "1.7.30")
    implementation(files("$projectDir/libs/logback-core-1.2.3.jar"))
    implementation(files("$projectDir/libs/logback-classic-1.2.3.jar"))

    // Add dependencies of forms
    implementation(group = "com.intellij", name = "forms_rt", version = "7.0.3")

    // Missing helpers and common utils in java
    implementation(group="org.apache.commons", name="commons-lang3", version="3.11")

////////////////////////////////////////////////////////////////////////////
    // Twelve monkeys imageio (supports jpeg, TIFF, HDR)
    implementation("com.twelvemonkeys.imageio:imageio-core:3.6")
    implementation("com.twelvemonkeys.imageio:imageio-hdr:3.6")
    implementation("com.twelvemonkeys.imageio:imageio-jpeg:3.6")
    implementation("com.twelvemonkeys.imageio:imageio-metadata:3.6")
    implementation("com.twelvemonkeys.imageio:imageio-tiff:3.6")
//////////////////////////////////////////////////
    //jxmapviewer2 https://github.com/msteiger/jxmapviewer2
    implementation(group = "org.jxmapviewer", name = "jxmapviewer2", version = "2.6")


    // Testing dependencies
    testImplementation(group = "junit", name = "junit", version = "4.12")
    testImplementation(group = "com.github.stefanbirkner", name = "system-rules", version = "1.19.0")
    //testImplementation(group = "ch.qos.logback", name = "logback-core", version = "1.2.3")
    //testImplementation(group = "ch.qos.logback", name = "logback-classic", version = "1.2.3")
    testImplementation(files("$projectDir/libs/logback-core-1.2.3.jar"))
    testImplementation(files("$projectDir/libs/logback-classic-1.2.3.jar"))

}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    // Undo version 11 again. 95% or more of OSes and distributions still use java 8
    // Redo java_11. We will deliver a jre11 if neccessary. Simple as that
    //sourceCompatibility = JavaVersion.VERSION_11
    //targetCompatibility = JavaVersion.VERSION_11

}

// New fatJar Gradle/kotlin way
val fatJar = task("fatJar", type = Jar::class) {
    baseName = "${project.name}-fat"
    manifest {
        attributes["Implementation-Title"] = "Gradle Jar File Example"
        //attributes["Implementation-Version"] = version
        attributes["Main-Class"] = project.ext["mainClassName"] as String
        attributes["Build-Timestamp"] = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ").format(Date())
        attributes["Created-By"] = "Gradle ${gradle.gradleVersion}"
        attributes["Author"] = "Harry van der Wolf"
        attributes["SplashScreen-Image"] = "jimagefuser-splashlogo.png"
        attributes["Multi-Release"] = "true"
    }
    from(configurations.runtimeClasspath.get().map({ if (it.isDirectory) it else zipTree(it) }))
    with(tasks.jar.get() as CopySpec)
//    doLast {
//        def servicesDir = file(
//    }
}

tasks {
    "build" {
        dependsOn(fatJar)
    }
}

//task copyServices(type: Copy) {
//    from 'TwelveMonkeys/META-INF/services/'
//    include '*'
//    into 'build/tmp/fatJar'
//}

val jar by tasks.getting(Jar::class) {
    manifest {
        attributes["Main-Class"] = project.ext["mainClassName"] as String
        attributes["Build-Timestamp"] = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ").format(Date())
        attributes["Created-By"] = "Gradle ${gradle.gradleVersion}"
        attributes["Author"] = "Harry van der Wolf"
        attributes["SplashScreen-Image"] = "jimagefuser-splashlogo.png"
        attributes["Multi-Release"] = "true"
    }
}

application {
    // Define the main class for the application
    mainClassName = project.ext["mainClassName"] as String
}


idea {
    module {
        outputDir = file("build/resources/main")
        testOutputDir = file("build/resources/test")
    }
}


